### ISSUE TITLE
Reason for v0.2 ?

### ISSUE THREAD

**Issue by synnack** [iorodeo/ph_featherwing#1]
Hi,

Cool project. Can I ask what was wrong with v0.1 other than more expensive parts (LMP7721) ? This part seems missing in the project history. It seems to match what I'm doing in a board and I'm interested in your experience with these circuits.

Thanks!

Wilco

**Comment by iorodeo** [comment]
The primary reason for the design change from v0.1 to v0.2 was to reduce manufacturing costs.  It wasn't due to any issue with the v0.1 design.  The design was modified to only use components which are stocked by the PCB manufacturer/assembler.  Doing this enables us to get the boards made very quickly and at lower cost.   Moving to the lower cost op amp (from the LMP7721) helped as well, but it was more of a side a effect.

**Comment by synnack** [comment]
Thank you for your reply!
